directories:
  output: release
  buildResources: build
appId: com.hts.facefilter
productName: FaceFilter
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
mac:
  target: dmg
  category: public.app-category.utilities
  hardenedRuntime: false
  gatekeeperAssess: false
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: FaceFilter
electronVersion: 33.3.1
